class Country:
   def __init__(self, name: str, flag: str):
      self.name = name
      self.flag = flag

   def __str__(self) -> str:
      return f"{self.name}, {self.flag}"

def getCountry(country: str) -> Country:
   """Returns a Country object from the country code."""
   if country == "" or not country:
      raise ValueError("Country code cannot be empty.")
   
   country = country.upper()

   countryTuple = countries.get(country)

   # This is raised when there is a country that isn't in the countries dictionary
   if countryTuple is None:
      countries[country] = (country, DEFAULT_LARGE_IMAGE)

   # Raised if there isn't an image link
   elif countryTuple[1] == "":
      countries[country] = (countryTuple[0], DEFAULT_LARGE_IMAGE)

   countryName = countries[country][0]
   flag = countries[country][1]

   return Country(countryName, flag)

DEFAULT_LARGE_IMAGE = "hoi4-logo2"

# List of countries, add more if you want
countries: dict[str, tuple[str, str]] = {

   # Countries that have more than one tag:
   # ITA, SOV, FRA, SPR, BUL, D##

   # especial case for the civil war:
   "D##" : ("Civil War Country", DEFAULT_LARGE_IMAGE),

   # handling the special cases
   # Idk why they have more tags, since the game only uses the first one. But I'll add them anyway.
   "SOV" : ("Soviet Union", "sov"),
   "ITA" : ("Italy", "ita"),
   "SPR" : ("Spain", "spr"), 
   "SPA" : ("Nationalist Spain", "spa"),
   "SPD" : ("Republican Spain", "spd"),
   "BUL" : ("Bulgaria", "bul"),
   "FRA" : ("France", "fra"),
   "VIC" : ("France", "vic"), # wheres free france?

   # Initial countries:
   "AFG": ("Afghanistan", "afg"),
   "ALB": ("Albania", "alb"),
   "ARG": ("Argentina", "arg"),
   "AFA": ("Sultanate of Aussa", "afa"),
   "AST": ("Australia", "ast"),
   "AUS": ("Austria", "aus"),
   "BEL": ("Belgium", "bel"),
   "BHU": ("Bhutan", "bhu"),
   "BOL": ("Bolivian Republic", "bol"),
   "BRA": ("Brazil", "bra"),
   "MAL": ("British Malaya", "mal"),
   "RAJ": ("British Raj", "raj"),
   "CAN": ("Dominion of Canada", "can"),
   "CHL": ("Chile", "chl"),
   "CHI": ("China", "chi"),
   "COL": ("Colombia", "col"),
   "PRC": ("Communist China", "prc"),
   "COS": ("Costa Rica", "cos"),
   "CUB": ("Cuba", "cub"),
   "CZE": ("Czechoslovakia", "cze"),
   "DEN": ("Denmark", "den"),
   "DOM": ("Dominican Republic", "dom"),
   "INS": ("Dutch East Indies", "ins"),
   "ECU": ("Ecuador", "ecu"),
   "ELS": ("El Salvador", "els"),
   "EST": ("Estonia", "est"),
   "ETH": ("Ethiopia", "eth"),
   "FIN": ("Finland", "fin"),
   "GER": ("German Reich", "ger"),
   "GRE": ("Kingdom of Greece", "gre"),
   "GXC": ("Guangxi Clique", "gxc"),
   "GUA": ("Guatemala", "gua"),
   "HAI": ("Haiti", "hai"),
   "HON": ("Honduras", "hon"),
   "HUN": ("Kingdom of Hungary", "hun"),
   "ICE": ("Iceland", "ice"),
   "PER": ("Iran", "per"),
   "IRQ": ("Iraq", "irq"),
   "IRE": ("Ireland", "ire"),
   "JAP": ("Japan", "jap"),
   "LAT": ("Latvia", "lat"),
   "LIB": ("Liberia", "lib"),
   "LIT": ("Lithuania", "lit"),
   "LUX": ("Luxembourg", "lux"),
   "MAN": ("Manchukuo", "man"),
   "MEN": ("Mengkukuo", "men"),
   "MEX": ("Mexico", "mex"),
   "MON": ("Mongolia", "mon"),
   "NEP": ("Nepal", "nep"),
   "HOL": ("Netherlands", "hol"),
   "NZL": ("New Zealand", "nzl"),
   "NIC": ("Nicaragua", "nic"),
   "NOR": ("Norway", "nor"),
   "OMA": ("Oman", "oma"),
   "PAN": ("Panama", "pan"),
   "PAR": ("Republic of Paraguay", "par"),
   "PRU": ("Peru", "pru"),
   "PHI": ("Philippines", "phi"),
   "POL": ("Poland", "pol"),
   "POR": ("Portugal", "por"),
   "ROM": ("Romania", "rom"),
   "SAU": ("Saudi Arabia", "sau"),
   "SHX": ("Shanxi", "shx"),
   "SIA": ("Siam", "sia"),
   "SIK": ("Sinkiang", "sik"),
   "SAF": ("South Africa", "saf"),
   "SWE": ("Sweden", "swe"),
   "SWI": ("Switzerland", "swi"),
   "TAN": ("Tannu Tuva", "tan"),
   "TIB": ("Tibet", "tib"),
   "TUR": ("Turkey", "tur"),
   "ENG": ("United Kingdom", "eng"),
   "USA": ("United States", "usa"),
   "URG": ("Uruguay", "urg"),
   "VEN": ("Venezuela", "ven"),
   "XSM": ("Xibei San Ma", "xsm"),
   "YEM": ("Yemen", "yem"),
   "YUG": ("Yugoslavia", "yug"),
   "YUN": ("Yunnan", "yun"),

   # Released countries:
   "ABK" : ("Abkhazia", "https://hoi4.paradoxwikis.com/images/b/be/Abkhazia.png"),
   "ADU" : ("Al-Andalus", "https://hoi4.paradoxwikis.com/images/9/9f/Al-Andalus.png"),
   "ALG" : ("Algeria", "https://hoi4.paradoxwikis.com/images/4/40/Algeria.png"),
   "ALT" : ("Altai", "https://hoi4.paradoxwikis.com/images/c/c7/Altai.png"),
   "ANG" : ("Angola", "https://hoi4.paradoxwikis.com/images/c/c4/Angola.png"),
   "ARM" : ("Armenia", "https://hoi4.paradoxwikis.com/images/9/90/Republic_of_Armenia.png"),
   "AZR" : ("Azerbaijan", "https://hoi4.paradoxwikis.com/images/0/05/Azerbaijan.png"),
   "BAH" : ("Bahamas", "https://hoi4.paradoxwikis.com/images/3/33/Commonwealth_of_the_Bahamas.png"),
   "BAN" : ("Bangladesh", "https://hoi4.paradoxwikis.com/images/9/9e/Bangladesh.png"),
   "BSK" : ("Bashkortostan", "https://hoi4.paradoxwikis.com/images/0/05/Bashkortostan.png"),
   "NAV" : ("Navarra", "https://hoi4.paradoxwikis.com/images/c/c8/Basque_Country.png"),
   "BAY" : ("Bavaria", "https://i.imgur.com/4LkDK0w.png"),
   "BLR" : ("Belarus", "https://hoi4.paradoxwikis.com/images/5/5c/Belarus.png"),
   "BLZ" : ("Belize", "https://hoi4.paradoxwikis.com/images/d/dd/Belize.png"),
   "BEG" : ("Benishangul-Gumuz Nation", "https://hoi4.paradoxwikis.com/images/9/9e/Bangladesh.png"),
   "BOS" : ("Bosnia", "https://i.imgur.com/1EzEwR4.png"),
   "BOT" : ("Botswana", "https://hoi4.paradoxwikis.com/images/1/1e/Botswana.png"),
   "BAS" : ("British Antilles", "https://hoi4.paradoxwikis.com/images/2/29/United_Kingdom.png"), # Using UK Flag
   "BRI" : ("Brittany", "https://hoi4.paradoxwikis.com/images/1/1c/Brittany.png"),
   "BUK" : ("Bukhara", "https://hoi4.paradoxwikis.com/images/1/14/Bukharan_Jadidist_Republic.png"),
   "BRM" : ("Burma", "https://hoi4.paradoxwikis.com/images/7/78/Burma.png"),
   "BRD" : ("Burundi", "https://hoi4.paradoxwikis.com/images/6/63/Burundi.png"),
   "BYA" : ("Buryatia", "https://hoi4.paradoxwikis.com/images/2/2c/Republic_of_Buryatia.png"),
   "CAM" : ("Cambodia", "https://hoi4.paradoxwikis.com/images/9/94/Republic_of_Cambodia.png"),
   "CMR" : ("Cameroon", "https://hoi4.paradoxwikis.com/images/9/92/Cameroon.png"),
   "CAT" : ("Catalonia", "https://i.imgur.com/qucdBrZ.png"),
   "CAY" : ("Cayenne", "https://i.imgur.com/vH2hzqz.png"),
   "CAR" : ("Central African Republic", "https://hoi4.paradoxwikis.com/images/d/d3/Central_African_Republic.png"),
   "CHA" : ("Chad", "https://hoi4.paradoxwikis.com/images/7/79/Chad.png"),
   "CIN" : ("Chechen-Ingush Republic", "https://i.imgur.com/CSWCRN2.jpeg"),
   "CKK" : ("Chukotka", "https://i.imgur.com/ftpUAMw.png"),
   "CHU" : ("Chuvashia", "https://hoi4.paradoxwikis.com/images/f/fa/Chuvashia.png"),
   "COR" : ("Corsica", "https://i.imgur.com/0y63AmO.png"),
   "CSA" : ("Confederacy of American States", "https://hoi4.paradoxwikis.com/images/0/0a/Confederacy_of_American_States.png"),
   "RCG" : ("Congo-Brazzaville", "https://hoi4.paradoxwikis.com/images/f/fa/Congo-Brazzaville.png"),
   "IVO" : ("Côte d'Ivoire", "https://hoi4.paradoxwikis.com/images/7/7f/C%C3%B4te_d%27Ivoire.png"),
   "CRI" : ("Crimea", "https://hoi4.paradoxwikis.com/images/6/64/Crimea.png"),
   "CRO" : ("Croatia", "https://hoi4.paradoxwikis.com/images/b/bb/Independent_State_of_Croatia.png"),
   "CYP" : ("Cyprus", "https://hoi4.paradoxwikis.com/images/2/2b/Republic_of_Cyprus.png"),
   "DAG" : ("Dagestan", "https://i.imgur.com/cxnthyw.png"),
   "DAH" : ("Dahomey", "https://hoi4.paradoxwikis.com/images/f/f1/Dahomey.png"),
   "DNZ" : ("Danzig", "https://hoi4.paradoxwikis.com/images/d/d8/Free_City_of_Danzig.png"),
   "DJI" : ("Djibouti", "https://hoi4.paradoxwikis.com/images/e/e2/Djibouti.png"),
   "DON" : ("Don Host", "https://i.imgur.com/DjrdiB4.png"),
   "AOI" : ("Italian State of East Africa", "https://hoi4.paradoxwikis.com/images/2/22/Italian_State_of_East_Africa.png"),
   "DDR" : ("East Germany", "https://hoi4.paradoxwikis.com/images/f/f2/East_Germany.png"),
   "EGY" : ("Kingdom of Egypt", "https://hoi4.paradoxwikis.com/images/7/7b/Kingdom_of_Egypt.png"),
   "EQG" : ("Equatorial Guinea", "https://hoi4.paradoxwikis.com/images/f/f5/Equatorial_Guinea.png"),
   "ERI" : ("Eritrea", "https://hoi4.paradoxwikis.com/images/8/8b/Eritrea.png"),
   "FER" : ("Far Eastern Republic", "https://hoi4.paradoxwikis.com/images/0/0a/Far_Eastern_Republic.png"),
   "GAB" : ("Gabon", "https://hoi4.paradoxwikis.com/images/e/e7/Gabon.png"),
   "GLC" : ("Galicia", "https://hoi4.paradoxwikis.com/images/1/11/Galicia.png"),
   "GBA" : ("Gambela", "https://hoi4.paradoxwikis.com/images/a/ad/Gambela.png"),
   "GAM" : ("Gambia", "https://hoi4.paradoxwikis.com/images/a/a0/The_Gambia.png"),
   "GEO" : ("Georgia", "https://hoi4.paradoxwikis.com/images/d/d1/Republic_of_Georgia.png"),
   "GHA" : ("Ghana", "https://hoi4.paradoxwikis.com/images/8/88/Ghana.png"),
   "GDL" : ("Guadeloupe", "https://i.imgur.com/n1UPF8e.png"),
   "GNA" : ("Guinea", "https://hoi4.paradoxwikis.com/images/b/b2/Guinea.png"),
   "GNB" : ("Guinea-Bissau", "https://hoi4.paradoxwikis.com/images/6/67/Guinea-Bissau.png"),
   "GYA" : ("Guyana", "https://i.imgur.com/oH9tyzR.png"),
   "HAR" : ("Harar", "https://i.imgur.com/v08C5mU.png"),
   "HAW" : ("Hawaii", r"https://hoi4.paradoxwikis.com/images/d/d7/Kingdom_of_Hawai%27i.png"),
   "HRZ" : ("Herzegovina", "https://hoi4.paradoxwikis.com/images/f/f8/Herzegovina.png"),
   "ICE" : ("Iceland", "https://hoi4.paradoxwikis.com/images/c/c1/Iceland.png"),
   "ISR" : ("Israel", "https://hoi4.paradoxwikis.com/images/9/94/Israel.png"),
   "JAM" : ("Jamaica", "https://hoi4.paradoxwikis.com/images/e/e7/Jamaica.png"),
   "JOR" : ("Jordan", "https://hoi4.paradoxwikis.com/images/e/e4/Jordan.png"),
   "KBK" : ("Kabardino Balkaria", "https://hoi4.paradoxwikis.com/images/a/ab/Federal_Republic_of_Kabardins_and_Karachay-Balkars.png"),
   "KAL" : ("Kalmykia", "https://hoi4.paradoxwikis.com/images/8/8d/Kalmykia.png"),
   "KKP" : ("Karakalpakstan", "https://hoi4.paradoxwikis.com/images/f/ff/Republic_of_Karakalpakstan.png"),
   "KAR" : ("Karelia", "https://hoi4.paradoxwikis.com/images/d/d1/Karelia.png"),
   "KSH" : ("Kashubia", "https://hoi4.paradoxwikis.com/images/c/ca/Kashubia.png"),
   "KAZ" : ("Kazakhstan", "https://hoi4.paradoxwikis.com/images/0/0e/Kazakhstan.png"),
   "KEN" : ("Kenya", "https://hoi4.paradoxwikis.com/images/b/b9/Kenya.png"),
   "KHA" : ("Khakassia", "https://i.imgur.com/wnoTtHs.gif"), # Only img I could find of this flag, need to test if Discord API accepts .gif
   "KHI" : ("Khiva", "https://hoi4.paradoxwikis.com/images/a/a0/Khivan_Jadidist_Republic.png"),
   "KOM" : ("Komi", "https://hoi4.paradoxwikis.com/images/7/74/Komi_Republic.png"),
   "KOR" : ("Korea", "https://hoi4.paradoxwikis.com/images/4/45/Korea.png"),
   "KOS" : ("Kosovo", "https://hoi4.paradoxwikis.com/images/a/a9/Kosovo.png"),
   "KUB" : ("Kuban", "https://i.imgur.com/GBRFUnx.png"),
   "KUW" : ("Kuwait", "https://hoi4.paradoxwikis.com/images/5/5c/Kuwait.png"),
   "KUR" : ("Kurdistan", "https://hoi4.paradoxwikis.com/images/9/95/Kurdistan.png"),
   "KYR" : ("Kyrgyzstan", "https://hoi4.paradoxwikis.com/images/c/ce/Kyrgyzstan.png"),
   "LAO" : ("Laos", "https://hoi4.paradoxwikis.com/images/1/16/Republic_of_Laos.png"),
   "LEB" : ("Lebanon", "https://hoi4.paradoxwikis.com/images/3/36/Lebanon.png"),
   "LBA" : ("Libya", "https://hoi4.paradoxwikis.com/images/4/45/Libya.png"),
   "LBV" : ("Lombardy-Venetia", "https://i.imgur.com/MWYmgso.png"),
   "MAC" : ("Macedonia", "https://hoi4.paradoxwikis.com/images/d/d2/Macedonia.png"),
   "MAD" : ("Madagascar", "https://hoi4.paradoxwikis.com/images/b/b3/Republic_of_Madagascar.png"),
   "MLW" : ("Malawi", "https://hoi4.paradoxwikis.com/images/0/08/Malawi.png"),
   "MLD" : ("Maldives", "https://hoi4.paradoxwikis.com/images/a/aa/Maldives.png"),
   "MLI" : ("Mali", "https://hoi4.paradoxwikis.com/images/f/f0/Mali.png"),
   "MLT" : ("Malta", "https://hoi4.paradoxwikis.com/images/1/10/Malta.png"),
   "MEL" : ("Mari El", "https://hoi4.paradoxwikis.com/images/c/cb/Mari_El.png"),
   "GUM" : ("Mariana Federation", "https://hoi4.paradoxwikis.com/images/4/44/Mariana_Federation.png"),
   "MRT" : ("Mauritania", "https://hoi4.paradoxwikis.com/images/f/f2/Mauritania.png"),
   "MEK" : ("Mecklenburg", "https://i.imgur.com/pkzTyCX.png"),
   "FIJ" : ("Fiji", "https://hoi4.paradoxwikis.com/images/2/2f/Melanesian_Federation.png"),
   "FSM" : ("Micronesia", "https://hoi4.paradoxwikis.com/images/0/03/Federated_States_of_Micronesia.png"),
   "MOL" : ("Moldova", "https://hoi4.paradoxwikis.com/images/3/3b/Moldova.png"),
   "MNT" : ("Montenegro", "https://hoi4.paradoxwikis.com/images/c/cd/Republic_of_Montenegro.png"),
   "MOR" : ("Morocco", "https://hoi4.paradoxwikis.com/images/7/7f/Kingdom_of_Morocco.png"),
   "MZB" : ("Mozambique", "https://hoi4.paradoxwikis.com/images/1/19/Mozambique.png"),
   "NMB" : ("Namibia", "https://hoi4.paradoxwikis.com/images/c/ce/Namibia.png"),
   "NEN" : ("Nenetsia", "https://hoi4.paradoxwikis.com/images/6/6e/Nenetsia.png"),
   "CRC" : ("Netherlands Antilles", "https://hoi4.paradoxwikis.com/images/4/46/Netherlands_Antilles.png"),
   "NGR" : ("Niger", "https://hoi4.paradoxwikis.com/images/7/72/Niger.png"),
   "NGA" : ("Nigeria", "https://hoi4.paradoxwikis.com/images/5/59/Nigeria.png"),
   "NIR" : ("Northern Ireland", "https://hoi4.paradoxwikis.com/images/1/12/Northern_Ireland.png"),
   "NOA" : ("North Ossetia-Alania", "https://hoi4.paradoxwikis.com/images/e/ea/North_Ossetia-Alania.png"),
   "OCC" : ("Occitania", "https://hoi4.paradoxwikis.com/images/a/a9/Occitania.png"),
   "ORO" : ("Oromia", "https://hoi4.paradoxwikis.com/images/e/e9/Oromia.png"),
   "OVO" : ("Ostyak Vogulia", "https://hoi4.paradoxwikis.com/images/d/d9/Ostyak-Vogul_National_Republic.png"),
   "PAK" : ("Pakistan", "https://hoi4.paradoxwikis.com/images/f/f3/Pakistan.png"),
   "PAL" : ("Palestine", "https://hoi4.paradoxwikis.com/images/1/1e/Palestine.png"),
   "PAP" : ("Papal States", "https://hoi4.paradoxwikis.com/images/f/f0/Papal_States.png"),
   "PNG" : ("Papua New Guinea", "https://hoi4.paradoxwikis.com/images/e/ed/Papua_New_Guinea.png"),
   "PRE" : ("Prussia", "https://i.imgur.com/huWWo2P.png"),
   "PUE" : ("Puerto Rico", "https://hoi4.paradoxwikis.com/images/8/87/Puerto_Rico.png"),
   "QAT" : ("Qatar", "https://hoi4.paradoxwikis.com/images/0/00/Republic_of_Qatar.png"),
   "QEM" : ("Qemant State", "https://hoi4.paradoxwikis.com/images/0/06/Qemant_State.png"),
   "RIF" : ("Rif", "https://hoi4.paradoxwikis.com/images/6/60/Republic_of_the_Rif.png"),
   "RWA" : ("Rwanda", "https://i.imgur.com/PGcoWPx.png"),
   "WES" : ("Western Sahara", "https://hoi4.paradoxwikis.com/images/8/88/Sahrawi_Arab_Democratic_Republic.png"),
   "YAK" : ("Sakha Republic", "https://hoi4.paradoxwikis.com/images/3/39/Sakha_Republic.png"),
   "SAM" : ("Samoa", "https://hoi4.paradoxwikis.com/images/4/45/Independent_State_of_Samoa.png"),
   "SPM" : ("Sardinia-Piedmont", "https://hoi4.paradoxwikis.com/images/2/22/Sardinia-Piedmont.png"),
   "SAX" : ("Saxony", "https://hoi4.paradoxwikis.com/images/0/0a/Kingdom_of_Saxony.png"),
   "SHL" : ("Schleswig-Holstein", "https://i.imgur.com/uJ4Rz2R.png"),
   "SCO" : ("Scotland", "https://hoi4.paradoxwikis.com/images/2/27/Scotland.png"),
   "SEN" : ("Senegal", "https://hoi4.paradoxwikis.com/images/2/22/Senegal.png"),
   "SER" : ("Serbia", "https://hoi4.paradoxwikis.com/images/7/76/Serbia.png"),
   "SID" : ("Sidamo", "https://i.imgur.com/OEfH3Rc.png"),
   "SIE" : ("Sierra Leone", "https://hoi4.paradoxwikis.com/images/b/bc/Kingdom_of_Sierra_Leone.png"),
   "SIL" : ("Silesia", "https://hoi4.paradoxwikis.com/images/f/f7/Silesia.png"),
   "SLO" : ("Slovakia", "https://hoi4.paradoxwikis.com/images/8/89/Slovakia.png"),
   "SLV" : ("Slovenia", "https://hoi4.paradoxwikis.com/images/3/32/Slovenia.png"),
   "SOL" : ("Solomon Islands", "https://hoi4.paradoxwikis.com/images/1/19/Solomon_Islands.png"),
   "SOM" : ("Somalia", "https://i.imgur.com/Y8Drza3.png"),
   "SRL" : ("Sri Lanka", "https://hoi4.paradoxwikis.com/images/6/64/Democratic_Socialist_Republic_of_Sri_Lanka.png"),
   "SUD" : ("Sudan", "https://hoi4.paradoxwikis.com/images/3/38/Sudan.png"),
   "SUR" : ("Suriname", "https://hoi4.paradoxwikis.com/images/c/c9/Republic_of_Suriname.png"),
   "SYR" : ("Syria", "https://hoi4.paradoxwikis.com/images/0/0f/Syria.png"),
   "TAH" : ("Tahiti", "https://hoi4.paradoxwikis.com/images/0/0c/Tahiti.png"),
   "TAJ" : ("Tajikistan", "https://hoi4.paradoxwikis.com/images/c/cf/Republic_of_Tajikistan.png"),
   "TZN" : ("Tanzania", "https://hoi4.paradoxwikis.com/images/6/61/Tanzania.png"),
   "TAT" : ("Tatarstan", "https://hoi4.paradoxwikis.com/images/b/ba/Tatarstan.png"),
   "TAY" : ("Taymyria", "https://hoi4.paradoxwikis.com/images/e/e1/Taymyria.png"),
   "TIG" : ("Tigray", "https://hoi4.paradoxwikis.com/images/8/86/Tigray.png"),
   "TOG" : ("Togo", "https://hoi4.paradoxwikis.com/images/9/98/Togo.png"),
   "TRA" : ("Transylvania", "https://hoi4.paradoxwikis.com/images/8/8f/Transylvania.png"),
   "TRI" : ("Trinidad and Tobago", "https://hoi4.paradoxwikis.com/images/d/d7/Republic_of_Trinidad_and_Tobago.png"),
   "TUN" : ("Tunisia", "https://hoi4.paradoxwikis.com/images/0/08/Tunisia.png"),
   "TMS" : ("Turkmenistan", "https://hoi4.paradoxwikis.com/images/b/b6/Republic_of_Turkmenistan.png"),
   "TOS" : ("Tuscany", "https://i.imgur.com/TdK1iAY.jpg"),
   "TTS" : ("Two Sicilies", "https://i.imgur.com/9bm3H1Z.png"),
   "UDM" : ("Udmurtia", "https://hoi4.paradoxwikis.com/images/5/53/Udmurtia.png"),
   "UGA" : ("Uganda", "https://hoi4.paradoxwikis.com/images/4/4c/Uganda.png"),
   "UKR" : ("Ukraine", "https://hoi4.paradoxwikis.com/images/1/1a/Ukraine.png"),
   "USB" : ("Unaligned States of America", "https://hoi4.paradoxwikis.com/images/3/32/United_States.png"), # Using US Flag
   "UAE" : ("United Arab Emirates", "https://hoi4.paradoxwikis.com/images/6/66/United_Arab_Emirates.png"),
   "VOL" : ("Upper Volta", "https://hoi4.paradoxwikis.com/images/b/b8/Upper_Volta.png"),
   "UZB" : ("Uzbekistan", "https://hoi4.paradoxwikis.com/images/2/29/Republic_of_Uzbekistan.png"),
   "VIN" : ("Vietnam", "https://hoi4.paradoxwikis.com/images/9/93/Republic_of_Vietnam.png"),
   "VLA" : ("Vladivostok", "https://hoi4.paradoxwikis.com/images/6/65/Vladivostok_Independent_Republic.png"),
   "VGE" : ("Volga Germany", "https://hoi4.paradoxwikis.com/images/f/f4/Republic_of_Volga_Germany.png"),
   "WLS" : ("Wales", "https://hoi4.paradoxwikis.com/images/d/d9/Wales.png"),
   "WGR" : ("West Germany", "https://hoi4.paradoxwikis.com/images/c/cc/West_Germany.png"),
   "HAN" : ("Westphalia", "https://i.imgur.com/lBbQxjP.png"),
   "WUR" : ("Wurtemberg", "https://i.imgur.com/5G1N75q.png"),
   "YAM" : ("Yamalia", "https://hoi4.paradoxwikis.com/images/6/64/Yamalian_Republic.png"),
   "COG" : ("Zaire", "https://hoi4.paradoxwikis.com/images/5/55/Zaire.png"),
   "ZAM" : ("Zambia", "https://hoi4.paradoxwikis.com/images/a/ad/Zambia.png"),
   "ZIM" : ("Zimbabwe", "https://hoi4.paradoxwikis.com/images/5/57/Zimbabwe.png")

}
