class Country:
   def __init__(self, name: str, flag: str):
      self.name = name
      self.flag = flag
   
   def __str__(self) -> str:
      return f"{self.name}, {self.flag}"

HOI_ICON = "https://hoi4.paradoxwikis.com/images/8/8a/HoI4_icon.png"

# List of countries, add more if you want
countries: dict[str, tuple[str, str]] = {

   # Countries in this block of code have more than one tag or have a special case
   "ITA" : ("Italy", "https://hoi4.paradoxwikis.com/images/2/2a/Italy.png"),
   "SOV" : ("Soviet Union", "https://hoi4.paradoxwikis.com/images/6/67/Soviet_Union.png"),
   "FRA" : ("France", "https://hoi4.paradoxwikis.com/images/d/de/France.png"),
   "SPR" : ("Spain", "https://hoi4.paradoxwikis.com/images/2/2c/Nationalist_Spain.png"),
   "BUL" : ("Bulgaria", "https://hoi4.paradoxwikis.com/images/f/f4/Bulgaria.png"),
   "D##" : ("Vojvodina or Dalmatia", HOI_ICON), # Wiki doesn't have the full pictures & shares the same tag


   "AFG" : ('Afghanistan', 'https://hoi4.paradoxwikis.com/images/7/7d/Afghanistan.png'),
   "ALB" : ('Albania', 'https://hoi4.paradoxwikis.com/images/0/07/Albania.png'),
   "ARG" : ('Argentina', 'https://hoi4.paradoxwikis.com/images/b/bc/Sultanate_of_Aussa.png'),
   "AFA" : ('Sultanate of Aussa', 'https://hoi4.paradoxwikis.com/images/4/43/Australia.png'),
   "AST" : ('Australia', 'https://hoi4.paradoxwikis.com/images/7/7f/Austria.png'),
   "AUS" : ('Austria', 'https://hoi4.paradoxwikis.com/images/7/7f/Austria.png'),
   "BEL" : ('Belgium', 'https://hoi4.paradoxwikis.com/images/3/32/Belgium.png'),
   "BHU" : ('Bhutan', 'https://hoi4.paradoxwikis.com/images/8/85/Bhutan.png'),
   "BOL" : ('Bolivia', 'https://hoi4.paradoxwikis.com/images/3/38/Bolivia.png'),
   "BRA" : ('Brazil', 'https://hoi4.paradoxwikis.com/images/8/8c/Brazil.png'),
   "MAL" : ('British Malaya', 'https://hoi4.paradoxwikis.com/images/f/f7/British_Malaya.png'),
   "RAJ" : ('British Raj', 'https://hoi4.paradoxwikis.com/images/2/2f/British_Raj.png'),
   "CAN" : ('Dominion of Canada', 'https://hoi4.paradoxwikis.com/images/e/e1/Dominion_of_Canada.png'),
   "CHL" : ('Chile', 'https://hoi4.paradoxwikis.com/images/f/fa/Chile.png'),
   "CHI" : ('China', 'https://hoi4.paradoxwikis.com/images/8/81/China.png'),
   "COL" : ('Colombia', 'https://hoi4.paradoxwikis.com/images/8/80/Colombia.png'),
   "PRC" : ('Communist China', 'https://hoi4.paradoxwikis.com/images/1/1a/Communist_China.png'),
   "COS" : ('Costa Rica', 'https://hoi4.paradoxwikis.com/images/d/da/Costa_Rica.png'),
   "CUB" : ('Cuba', 'https://hoi4.paradoxwikis.com/images/6/6c/Cuba.png'),
   "CZE" : ('Czechoslovakia', 'https://hoi4.paradoxwikis.com/images/c/c1/Czechoslovakia.png'),
   "DEN" : ('Denmark', 'https://hoi4.paradoxwikis.com/images/6/69/Denmark.png'),
   "DOM" : ('Dominican Republic', 'https://hoi4.paradoxwikis.com/images/5/5b/Dominican_Republic.png'),
   "INS" : ('Dutch East Indies', 'https://hoi4.paradoxwikis.com/images/3/32/Netherlands.png'),
   "ECU" : ('Ecuador', 'https://hoi4.paradoxwikis.com/images/b/b2/Ecuador.png'),
   "ELS" : ('El Salvador', 'https://hoi4.paradoxwikis.com/images/5/5c/El_Salvador.png'),
   "EST" : ('Estonia', 'https://hoi4.paradoxwikis.com/images/6/6f/Estonia.png'),
   "ETH" : ('Ethiopia', 'https://hoi4.paradoxwikis.com/images/0/06/Ethiopia.png'),
   "FIN" : ('Finland', 'https://hoi4.paradoxwikis.com/images/c/c4/Finland.png'),
   "GER" : ('German Reich', 'https://hoi4.paradoxwikis.com/images/e/e9/German_Reich.png'),
   "GRE" : ('Kingdom of Greece', 'https://hoi4.paradoxwikis.com/images/8/8e/Kingdom_of_Greece.png'),
   "GXC" : ('Guangxi Clique', 'https://hoi4.paradoxwikis.com/images/6/68/Guangxi_Clique.png'),
   "GUA" : ('Guatemala', 'https://hoi4.paradoxwikis.com/images/5/55/Guatemala.png'),
   "HAI" : ('Haiti', 'https://hoi4.paradoxwikis.com/images/2/28/Haiti.png'),
   "HON" : ('Honduras', 'https://hoi4.paradoxwikis.com/images/0/09/Honduras.png'),
   "HUN" : ('Hungary', 'https://hoi4.paradoxwikis.com/images/5/53/Kingdom_of_Hungary.png'),
   "PER" : ('Iran', 'https://hoi4.paradoxwikis.com/images/d/d1/Iran.png'),
   "IRQ" : ('Iraq', 'https://hoi4.paradoxwikis.com/images/c/c4/Iraq.png'),
   "IRE" : ('Ireland', 'https://hoi4.paradoxwikis.com/images/4/4b/Ireland.png'),
   "JAP" : ('Japan', 'https://hoi4.paradoxwikis.com/images/f/fc/Japan.png'),
   "LAT" : ('Latvia', 'https://hoi4.paradoxwikis.com/images/7/7c/Latvia.png'),
   "LIB" : ('Liberia', 'https://hoi4.paradoxwikis.com/images/0/05/Liberia.png'),
   "LIT" : ('Lithuania', 'https://hoi4.paradoxwikis.com/images/d/d9/Lithuania.png'),
   "LUX" : ('Luxembourg', 'https://hoi4.paradoxwikis.com/images/3/3f/Luxembourg.png'),
   "MAN" : ('Manchukuo', 'https://hoi4.paradoxwikis.com/images/1/16/Manchukuo.png'),
   "MEN" : ('Mengkukuo', 'https://hoi4.paradoxwikis.com/images/4/4d/Mengkukuo.png'),
   "MEX" : ('Mexico', 'https://hoi4.paradoxwikis.com/images/0/0a/Mexico.png'),
   "MON" : ('Mongolia', 'https://hoi4.paradoxwikis.com/images/b/bc/Mongolia.png'),
   "NEP" : ('Nepal', 'https://hoi4.paradoxwikis.com/images/3/3a/Nepal.png'),
   "HOL" : ('Netherlands', 'https://hoi4.paradoxwikis.com/images/3/32/Netherlands.png'),
   "NZL" : ('New Zealand', 'https://hoi4.paradoxwikis.com/images/d/d9/New_Zealand.png'),
   "NIC" : ('Nicaragua', 'https://hoi4.paradoxwikis.com/images/7/7e/Republic_of_Nicaragua.png'),
   "NOR" : ('Norway', 'https://hoi4.paradoxwikis.com/images/0/0f/Norway.png'),
   "OMA" : ('Oman', 'https://hoi4.paradoxwikis.com/images/2/27/Oman.png'),
   "PAN" : ('Panama', 'https://hoi4.paradoxwikis.com/images/3/3f/Panama.png'),
   "PAR" : ('Paraguay', 'https://hoi4.paradoxwikis.com/images/5/57/Paraguay.png'),
   "PRU" : ('Peru', 'https://hoi4.paradoxwikis.com/images/a/a8/Peru.png'),
   "PHI" : ('Philippines', 'https://hoi4.paradoxwikis.com/images/3/3b/Philippines.png'),
   "POL" : ('Poland', 'https://hoi4.paradoxwikis.com/images/9/99/Poland.png'),
   "POR" : ('Portugal', 'https://hoi4.paradoxwikis.com/images/1/12/Portugal.png'),
   "ROM" : ('Romania', 'https://hoi4.paradoxwikis.com/images/8/8f/Romania.png'),
   "SAU" : ('Saudi Arabia', 'https://hoi4.paradoxwikis.com/images/1/1f/Saudi_Arabia.png'),
   "SHX" : ('Shanxi', 'https://hoi4.paradoxwikis.com/images/d/d0/Shanxi.png'),
   "SIA" : ('Siam', 'https://hoi4.paradoxwikis.com/images/7/7e/Siam.png'),
   "SIK" : ('Sinkiang', 'https://hoi4.paradoxwikis.com/images/b/b8/Sinkiang.png'),
   "SAF" : ('South Africa', 'https://hoi4.paradoxwikis.com/images/e/ef/South_Africa.png'),
   "SWE" : ('Sweden', 'https://hoi4.paradoxwikis.com/images/9/98/Sweden.png'),
   "SWI" : ('Switzerland', 'https://hoi4.paradoxwikis.com/images/0/01/Switzerland.png'),
   "TAN" : ('Tannu Tuva', 'https://hoi4.paradoxwikis.com/images/5/54/Tannu_Tuva.png'),
   "TIB" : ('Tibet', 'https://hoi4.paradoxwikis.com/images/0/03/Tibet.png'),
   "TUR" : ('Turkey', 'https://hoi4.paradoxwikis.com/images/b/b3/Turkey.png'),
   "ENG" : ('United Kingdom', 'https://hoi4.paradoxwikis.com/images/2/29/United_Kingdom.png'),
   "USA" : ('United States', 'https://hoi4.paradoxwikis.com/images/3/32/United_States.png'),
   "URG" : ('Uruguay', 'https://hoi4.paradoxwikis.com/images/2/29/Uruguay.png'),
   "VEN" : ('Venezuela', 'https://hoi4.paradoxwikis.com/images/5/5d/Venezuela.png'),
   "XSM" : ('Xibei San Ma', 'https://hoi4.paradoxwikis.com/images/6/6e/Xibei_San_Ma.png'),
   "YEM" : ('Yemen', 'https://hoi4.paradoxwikis.com/images/f/fc/Yemen.png'),
   "YUG" : ('Yugoslavia', 'https://hoi4.paradoxwikis.com/images/f/f3/Yugoslavia.png'),
   "YUN" : ('Yunnan', 'https://hoi4.paradoxwikis.com/images/3/3b/Yunnan.png'),
   "ABK" : ('Abkhazia', 'https://hoi4.paradoxwikis.com/images/b/be/Abkhazia.png'),
   "ADU" : ('Al-Andalus', 'https://hoi4.paradoxwikis.com/images/9/9f/Al-Andalus.png'),
   "ALG" : ('Algeria', 'https://hoi4.paradoxwikis.com/images/4/40/Algeria.png'),
   "ALT" : ('Altai', 'https://hoi4.paradoxwikis.com/images/c/c7/Altai.png'),
   "ANG" : ('Angola', 'https://hoi4.paradoxwikis.com/images/c/c4/Angola.png'),
   "ARM" : ('Armenia', 'link'),
   "AZR" : ('Azerbaijan', 'https://hoi4.paradoxwikis.com/images/0/05/Azerbaijan.png'),
   "BAH" : ('Bahamas', 'link'),
   "BAN" : ('Bangladesh', 'https://hoi4.paradoxwikis.com/images/9/9e/Bangladesh.png'),
   "BSK" : ('Bashkortostan', 'https://hoi4.paradoxwikis.com/images/0/05/Bashkortostan.png'),
   "NAV" : ('Navarra', 'link'),
   "BAY" : ('Bavaria', 'link'),
   "BLR" : ('Belarus', 'https://hoi4.paradoxwikis.com/images/5/5c/Belarus.png'),
   "BLZ" : ('Belize', 'https://hoi4.paradoxwikis.com/images/d/dd/Belize.png'),
   "BEG" : ('Benishangul-Gumuz Nation', 'link'),
   "BOS" : ('Bosnia', 'https://hoi4.paradoxwikis.com/images/a/ad/Bosnia.png'),
   "BOT" : ('Botswana', 'https://hoi4.paradoxwikis.com/images/1/1e/Botswana.png'),
   "BAS" : ('British Antilles', 'link'),
   "BRI" : ('Brittany', 'https://hoi4.paradoxwikis.com/images/1/1c/Brittany.png'),
   "BUK" : ('Bukhara', 'link'),
   "BRM" : ('Burma', 'https://hoi4.paradoxwikis.com/images/7/78/Burma.png'),
   "BRD" : ('Burundi', 'https://hoi4.paradoxwikis.com/images/6/63/Burundi.png'),
   "BYA" : ('Buryatia', 'link'),
   "CAM" : ('Cambodia', 'link'),
   "CMR" : ('Cameroon', 'https://hoi4.paradoxwikis.com/images/9/92/Cameroon.png'),
   "CAT" : ('Catalonia', 'link'),
   "CAY" : ('Cayenne', 'link'),
   "CAR" : ('Central African Republic', 'https://hoi4.paradoxwikis.com/images/d/d3/Central_African_Republic.png'),
   "CHA" : ('Chad', 'https://hoi4.paradoxwikis.com/images/7/79/Chad.png'),
   "CIN" : ('Chechnya Ingushetia', 'link'),
   "CKK" : ('Chukotka', 'link'),
   "CHU" : ('Chuvashia', 'https://hoi4.paradoxwikis.com/images/f/fa/Chuvashia.png'),
   "COR" : ('Corsica', 'link'),
   "CSA" : ('Confederacy of American States', 'https://hoi4.paradoxwikis.com/images/0/0a/Confederacy_of_American_States.png'),
   "RCG" : ('Congo-Brazzaville', 'https://hoi4.paradoxwikis.com/images/f/fa/Congo-Brazzaville.png'),
   "IVO" : ("Côte d'Ivoire", 'https://hoi4.paradoxwikis.com/images/7/7f/C%C3%B4te_d%27Ivoire.png'),
   "CRI" : ('Crimea', 'https://hoi4.paradoxwikis.com/images/6/64/Crimea.png'),
   "CRO" : ('Croatia', 'link'),
   "CYP" : ('Cyprus', 'link'),
   "DAG" : ('Dagestan', 'link'),
   "DAH" : ('Dahomey', 'https://hoi4.paradoxwikis.com/images/f/f1/Dahomey.png'),
   "DNZ" : ('Danzig', 'link'),
   "DJI" : ('Djibouti', 'https://hoi4.paradoxwikis.com/images/e/e2/Djibouti.png'),
   "DON" : ('Don', 'link'),
   "AOI" : ('Italian State of East Africa', 'https://hoi4.paradoxwikis.com/images/2/22/Italian_State_of_East_Africa.png'),
   "DDR" : ('East Germany', 'https://hoi4.paradoxwikis.com/images/f/f2/East_Germany.png'),
   "EGY" : ('Kingdom of Egypt', 'https://hoi4.paradoxwikis.com/images/7/7b/Kingdom_of_Egypt.png'),
   "EQG" : ('Equatorial Guinea', 'https://hoi4.paradoxwikis.com/images/f/f5/Equatorial_Guinea.png'),
   "ERI" : ('Eritrea', 'https://hoi4.paradoxwikis.com/images/8/8b/Eritrea.png'),
   "FER" : ('Far Eastern Republic', 'https://hoi4.paradoxwikis.com/images/0/0a/Far_Eastern_Republic.png'),
   "GAB" : ('Gabon', 'https://hoi4.paradoxwikis.com/images/e/e7/Gabon.png'),
   "GLC" : ('Galicia', 'https://hoi4.paradoxwikis.com/images/1/11/Galicia.png'),
   "GBA" : ('Gambela', 'https://hoi4.paradoxwikis.com/images/a/ad/Gambela.png'),
   "GAM" : ('Gambia', 'link'),
   "GEO" : ('Georgia', 'link'),
   "GHA" : ('Ghana', 'https://hoi4.paradoxwikis.com/images/8/88/Ghana.png'),
   "GDL" : ('Guadeloupe', 'link'),
   "GNA" : ('Guinea', 'https://hoi4.paradoxwikis.com/images/b/b2/Guinea.png'),
   "GNB" : ('Guinea-Bissau', 'https://hoi4.paradoxwikis.com/images/6/67/Guinea-Bissau.png'),
   "GYA" : ('Guyana', 'link'),
   "HAR" : ('Harar', 'link'),
   "HAW" : ('Hawaii', 'link'),
   "HRZ" : ('Herzegovina', 'https://hoi4.paradoxwikis.com/images/f/f8/Herzegovina.png'),
   "ICE" : ('Iceland', 'https://hoi4.paradoxwikis.com/images/c/c1/Iceland.png'),
   "ISR" : ('Israel', 'https://hoi4.paradoxwikis.com/images/9/94/Israel.png'),
   "JAM" : ('Jamaica', 'https://hoi4.paradoxwikis.com/images/e/e7/Jamaica.png'),
   "JOR" : ('Jordan', 'https://hoi4.paradoxwikis.com/images/e/e4/Jordan.png'),
   "KBK" : ('Kabardino Balkaria', 'link'),
   "KAL" : ('Kalmykia', 'https://hoi4.paradoxwikis.com/images/8/8d/Kalmykia.png'),
   "KKP" : ('Karakalpakstan', 'link'),
   "KAR" : ('Karelia', 'https://hoi4.paradoxwikis.com/images/d/d1/Karelia.png'),
   "KSH" : ('Kashubia', 'https://hoi4.paradoxwikis.com/images/c/ca/Kashubia.png'),
   "KAZ" : ('Kazakh', 'link'),
   "KEN" : ('Kenya', 'https://hoi4.paradoxwikis.com/images/b/b9/Kenya.png'),
   "KHA" : ('Khakassia', 'link'),
   "KHI" : ('Khiva', 'link'),
   "KOM" : ('Komi', 'link'),
   "KOR" : ('Korea', 'https://hoi4.paradoxwikis.com/images/4/45/Korea.png'),
   "KOS" : ('Kosovo', 'https://hoi4.paradoxwikis.com/images/a/a9/Kosovo.png'),
   "KUB" : ('Kuban', 'link'),
   "KUW" : ('Kuwait', 'https://hoi4.paradoxwikis.com/images/5/5c/Kuwait.png'),
   "KUR" : ('Kurdistan', 'https://hoi4.paradoxwikis.com/images/9/95/Kurdistan.png'),
   "KYR" : ('Kyrgyzstan', 'https://hoi4.paradoxwikis.com/images/c/ce/Kyrgyzstan.png'),
   "LAO" : ('Laos', 'link'),
   "LEB" : ('Lebanon', 'https://hoi4.paradoxwikis.com/images/3/36/Lebanon.png'),
   "LBA" : ('Libya', 'https://hoi4.paradoxwikis.com/images/4/45/Libya.png'),
   "LBV" : ('Lombardy-Venetia', 'link'),
   "MAC" : ('Macedonia', 'https://hoi4.paradoxwikis.com/images/d/d2/Macedonia.png'),
   "MAD" : ('Madagascar', 'link'),
   "MLW" : ('Malawi', 'https://hoi4.paradoxwikis.com/images/0/08/Malawi.png'),
   "MLD" : ('Maldives', 'https://hoi4.paradoxwikis.com/images/a/aa/Maldives.png'),
   "MLI" : ('Mali', 'https://hoi4.paradoxwikis.com/images/f/f0/Mali.png'),
   "MLT" : ('Malta', 'https://hoi4.paradoxwikis.com/images/1/10/Malta.png'),
   "MEL" : ('Mari El', 'https://hoi4.paradoxwikis.com/images/c/cb/Mari_El.png'),
   "GUM" : ('Guam', 'link'),
   "MRT" : ('Mauritania', 'https://hoi4.paradoxwikis.com/images/f/f2/Mauritania.png'),
   "MEK" : ('Mecklenburg', 'link'),
   "FIJ" : ('Fiji', 'link'),
   "FSM" : ('Micronesia', 'link'),
   "MOL" : ('Moldova', 'https://hoi4.paradoxwikis.com/images/3/3b/Moldova.png'),
   "MNT" : ('Montenegro', 'link'),
   "MOR" : ('Morocco', 'link'),
   "MZB" : ('Mozambique', 'https://hoi4.paradoxwikis.com/images/1/19/Mozambique.png'),
   "NMB" : ('Namibia', 'https://hoi4.paradoxwikis.com/images/c/ce/Namibia.png'),
   "NEN" : ('Nenetsia', 'https://hoi4.paradoxwikis.com/images/6/6e/Nenetsia.png'),
   "CRC" : ('Cura.C3.A7ao', 'link'),
   "NGR" : ('Niger', 'https://hoi4.paradoxwikis.com/images/7/72/Niger.png'),
   "NGA" : ('Nigeria', 'https://hoi4.paradoxwikis.com/images/5/59/Nigeria.png'),
   "NIR" : ('Northern Ireland', 'https://hoi4.paradoxwikis.com/images/1/12/Northern_Ireland.png'),
   "NOA" : ('North Ossetia-Alania', 'https://hoi4.paradoxwikis.com/images/e/ea/North_Ossetia-Alania.png'),
   "OCC" : ('Occitania', 'https://hoi4.paradoxwikis.com/images/a/a9/Occitania.png'),
   "ORO" : ('Oromia', 'https://hoi4.paradoxwikis.com/images/e/e9/Oromia.png'),
   "OVO" : ('Ostyak Vogulia', 'link'),
   "PAK" : ('Pakistan', 'https://hoi4.paradoxwikis.com/images/f/f3/Pakistan.png'),
   "PAL" : ('Palestine', 'https://hoi4.paradoxwikis.com/images/1/1e/Palestine.png'),
   "PAP" : ('Papal States', 'https://hoi4.paradoxwikis.com/images/f/f0/Papal_States.png'),
   "PNG" : ('Papua New Guinea', 'https://hoi4.paradoxwikis.com/images/e/ed/Papua_New_Guinea.png'),
   "PRE" : ('Prussia', 'link'),
   "PUE" : ('Puerto Rico', 'https://hoi4.paradoxwikis.com/images/8/87/Puerto_Rico.png'),
   "QAT" : ('Qatar', 'link'),
   "QEM" : ('Qemant State', 'https://hoi4.paradoxwikis.com/images/0/06/Qemant_State.png'),
   "RIF" : ('Rif', 'link'),
   "RWA" : ('Rwanda', 'https://hoi4.paradoxwikis.com/images/8/8a/Rwanda.png'),
   "WES" : ('Western Sahara', 'link'),
   "YAK" : ('Yakutia', 'link'),
   "SAM" : ('Samoa', 'link'),
   "SPM" : ('Sardinia-Piedmont', 'https://hoi4.paradoxwikis.com/images/2/22/Sardinia-Piedmont.png'),
   "SAX" : ('Saxony', 'link'),
   "SHL" : ('Schleswig-Holstein', 'link'),
   "SCO" : ('Scotland', 'https://hoi4.paradoxwikis.com/images/2/27/Scotland.png'),
   "SEN" : ('Senegal', 'https://hoi4.paradoxwikis.com/images/2/22/Senegal.png'),
   "SER" : ('Serbia', 'https://hoi4.paradoxwikis.com/images/7/76/Serbia.png'),
   "SID" : ('Sidamo', 'link'),
   "SIE" : ('Sierra Leone', 'link'),
   "SIL" : ('Silesia', 'https://hoi4.paradoxwikis.com/images/f/f7/Silesia.png'),
   "SLO" : ('Slovakia', 'https://hoi4.paradoxwikis.com/images/8/89/Slovakia.png'),
   "SLV" : ('Slovenia', 'https://hoi4.paradoxwikis.com/images/3/32/Slovenia.png'),
   "SOL" : ('Solomon Islands', 'https://hoi4.paradoxwikis.com/images/1/19/Solomon_Islands.png'),
   "SOM" : ('Somalia', 'link'),
   "SRL" : ('Sri Lanka', 'link'),
   "SUD" : ('Sudan', 'https://hoi4.paradoxwikis.com/images/3/38/Sudan.png'),
   "SUR" : ('Suriname', 'link'),
   "SYR" : ('Syria', 'https://hoi4.paradoxwikis.com/images/0/0f/Syria.png'),
   "TAH" : ('Tahiti', 'https://hoi4.paradoxwikis.com/images/0/0c/Tahiti.png'),
   "TAJ" : ('Tajikistan', 'link'),
   "TZN" : ('Tanzania', 'https://hoi4.paradoxwikis.com/images/6/61/Tanzania.png'),
   "TAT" : ('Tatarstan', 'https://hoi4.paradoxwikis.com/images/b/ba/Tatarstan.png'),
   "TAY" : ('Taymyria', 'https://hoi4.paradoxwikis.com/images/e/e1/Taymyria.png'),
   "TIG" : ('Tigray', 'https://hoi4.paradoxwikis.com/images/8/86/Tigray.png'),
   "TOG" : ('Togo', 'https://hoi4.paradoxwikis.com/images/9/98/Togo.png'),
   "TRA" : ('Transylvania', 'https://hoi4.paradoxwikis.com/images/8/8f/Transylvania.png'),
   "TRI" : ('Trinidad and Tobago', 'link'),
   "TUN" : ('Tunisia', 'https://hoi4.paradoxwikis.com/images/0/08/Tunisia.png'),
   "TMS" : ('Turkmenistan', 'link'),
   "TOS" : ('Tuscany', 'link'),
   "TTS" : ('Two Sicilies', 'link'),
   "UDM" : ('Udmurtia', 'https://hoi4.paradoxwikis.com/images/5/53/Udmurtia.png'),
   "UGA" : ('Uganda', 'https://hoi4.paradoxwikis.com/images/4/4c/Uganda.png'),
   "UKR" : ('Ukraine', 'https://hoi4.paradoxwikis.com/images/1/1a/Ukraine.png'),
   "USB" : ('USB', 'link'),
   "UAE" : ('United Arab Emirates', 'https://hoi4.paradoxwikis.com/images/6/66/United_Arab_Emirates.png'),
   "VOL" : ('Upper Volta', 'https://hoi4.paradoxwikis.com/images/b/b8/Upper_Volta.png'),
   "UZB" : ('Uzbekistan', 'link'),
   "VIN" : ('Vietnam', 'link'),
   "VLA" : ('Vladivostok', 'link'),
   "VGE" : ('Volga Germany', 'link'),
   "WLS" : ('Wales', 'https://hoi4.paradoxwikis.com/images/d/d9/Wales.png'),
   "WGR" : ('West Germany', 'https://hoi4.paradoxwikis.com/images/c/cc/West_Germany.png'),
   "HAN" : ('Westphalia', 'link'),
   "WUR" : ('Wurtemberg', 'link'),
   "YAM" : ('Yamalia', 'link'),
   "COG" : ('Zaire', 'https://hoi4.paradoxwikis.com/images/5/55/Zaire.png'),
   "ZAM" : ('Zambia', 'https://hoi4.paradoxwikis.com/images/a/ad/Zambia.png'),
   "ZIM" : ('Zimbabwe', 'https://hoi4.paradoxwikis.com/images/5/57/Zimbabwe.png')

}

def getCountry(country: str) -> Country:
   """Returns a Country object from the country code."""
   if country == "" or not country:
      raise ValueError("Country code cannot be empty.")
   
   country = country.upper()

   # This is raised when there is a country that isn't in the countries dictionary
   if countries.get(country) is None:
      countries[country] = (country, HOI_ICON)

   countryName = countries[country][0]
   flag = countries[country][1]

   return Country(countryName, flag)
